export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const PROJECT_IMPORT = 'PROJECT_IMPORT';

export const FETCH_PROJECT_CREATE_SUCCESS = 'FETCH_PROJECT_CREATE_SUCCESS';

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';

export const SAVE_PROJECT_REQUEST = 'SAVE_PROJECT_REQUEST';

export const FETCH_PROJECT_LOAD_REQUEST = 'FETCH_PROJECT_LOAD_REQUEST';
export const FETCH_PROJECT_LOAD_SUCCESS = 'FETCH_PROJECT_LOAD_SUCCESS';
export const FETCH_PROJECT_LOAD_FAILURE = 'FETCH_PROJECT_LOAD_FAILURE';

export const NODE_SELECTION_CHANGED = 'NODE_SELECTION_CHANGED';
export const NODE_ADD = 'NODE_ADD';
export const NODE_RENAME = 'NODE_RENAME';
export const NODE_DELETE = 'NODE_DELETE';
export const NODE_UPDATE = 'NODE_UPDATE';

export const NODE_PROPERTY_RENAME = 'NODE_PROPERTY_RENAME';
export const NODE_PROPERTY_UPDATE = 'NODE_PROPERTY_UPDATE';


export const VIEW_CREATED = 'VIEW_CREATED';
export const VIEW_SELECTION_CHANGED = 'VIEW_SELECTION_CHANGED';
export const VIEW_SET_AS_MAIN = 'VIEW_SET_AS_MAIN';

export const REGISTRY_UPDATE = 'REGISTRY_UPDATE';

export const REFRESHER_UPDATE = 'REFRESHER_UPDATE';